db.permissions.save({id: 2, name: "User", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 3, name: "Member", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 4, name: "Power User", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 20, name: "Donor", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 18, name: "Artist", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 5, name: "Elite", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 6, name: "VIP", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view"]});
db.permissions.save({id: 7, name: "Torrent Master", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 8, name: "Legend", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 9, name: "Celeb", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 10, name: "Community Moderator", staff: false, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 11, name: "Moderator", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 12, name: "Staff Leader", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 13, name: "Designer", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 14, name: "Coder", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete"]});
db.permissions.save({id: 1, name: "Admin", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete","site_users_edit"]});
db.permissions.save({id: 15, name: "SysOp", staff: true, values: ["site_torrents_comment","site_torrents_search","site_torrents_upload","site_torrents_view","site_torrents_download","site_torrents_tags_delete","site_torrents_tags_add","site_users_view","site_kb_search","site_kb_view","site_kb_new","site_kb_edit","site_kb_delete","site_users_edit"]});

